### ISSUE TITLE
Clean up irida-pipeline-plugins repository

### ISSUE THREAD

**Issue by pvanheus** [COMBAT-TB/irida-pipeline-plugins#13]
1. Move all pipelines that are not under active development to an `archived` folder
2. Fix or abandon CI integration
3. Update README to describe repository contents

@zipho can you help me identify which pipelines should be archived?

**Comment by zipho** [comment]
**Perhaps we can archive for the following directories:**

> raw
> sanbi-bvc-pipeline-plugin
> sars-cov-2-pipeline
> sars-cov
> tb-vcf-report-pipeline-plugin

If agree @pvanheus, will move them.

Not sure where the CI integration was going, will investigate and possibly abandon it.

**Comment by pvanheus** [comment]
@zipho yes, agree, archive those.

**Comment by zipho** [comment]
The README update is missing. 

What should the contents thereof cover @pvanheus ?
