### ISSUE TITLE
Cleanup output of TB Sample Report pipeline

### ISSUE THREAD

**Issue by pvanheus** [COMBAT-TB/irida-pipeline-plugins#9]
The current pipeline output shows outputs from zipped HTML that are unreadable and JSON that has little visual value.

The [IRIDA code](https://github.com/apetkau/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java#L380) hides zip, html and pdf output previews but the output name of the HTML outputs are mtbva_tb_variant_report_html and mtbva_tb_variant_dr_report_html. These names should be changed in the output workflow to ensure that they are not displayed.

The JSON output is named tb_profiler_json and should also be renamed to .json for easier filtering on the IRIDA end.

**Comment by pvanheus** [comment]
Current output has been cleaned up a bit "too much":

![image](https://user-images.githubusercontent.com/4154788/100979438-6bf5f580-354c-11eb-9c24-ea13ec8447f2.png)

What is needed in addition to what is shown there is:

1. TB VCF text report
2. TB VCF HTML report (downloadable - because this is a zip file)
3. SnpEff annotated VCF

The last item in the list is in addition to TBprofiler VCF.

**Comment by zipho** [comment]
Please verify as the plugin is updated[
![Screenshot_20201209_093917](https://user-images.githubusercontent.com/2108971/101599681-d4d4e600-3a02-11eb-965c-86e94d1f030f.png)
](url)
